--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/gamegam/Hypixel_Book
build-by-default: true
branches:
- main
projects:
  Hypixel_Book:
    path: "Hypixel_Book/Hypixel.png"
    icon: "Hypixel.png"
...
