---
#author the name of the book
#You can check that my own nickname is called with {name}!


author: Server

Title: Server Help


#Command allows the player to enable or disable /rule commands.
# true is activation false deactivation.
Command: true

#Since page is an array - paste something like this Example:
#-test
#-HI
#test is page 1
#Hi is page 2
page:
  - "Hello {name}"
  - "Test {name}"
...
